spring:
  application:
        name: remoteCompiler
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
 
hostname: demo

liquibase:
  enabled: true

server:
  port: 9000

loc:
  jarHome: /tmp/jar/
  scriptHome: /tmp/scripts/
  javaHome: /tmp/java/
  classHome: /tmp/class/