spring:
  application:
        name: remoteCompiler
  datasource:
        url: jdbc:mysql://192.168.150.75:3306/tpe?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: bullet
        driverClassName: com.mysql.jdbc.Driver
  logging:
        file: /tmp/application.log
        level:
          org.springframework: 'OFF'          

hostname: demo

liquibase:
  enabled: false

server:
  port: 9000
