language:
#  - java
  - cpp
  - c
#jdk:
#  - openjdk8
script: mvn clean verify
#dist: trusty
sudo: required
#language: c
cache: ccache
compiler:
  - gcc

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libxen-dev -y
  - sudo apt-get install --only-upgrade binutils gcc -y
  - git clone http://repo.rumpkernel.org/rumprun
  - cd rumprun
  - git submodule update --init
  - CC=cc ./build-rr.sh hw
