language:
#  - java
  - cpp
  - c
#jdk:
#  - openjdk8
env:
  global:
      - PATH="$$HOME/text-processor/rumprun/./rumprun/bin:/usr/lib/ccache:$PATH"
env:
   - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS=
   - RUMPRUN_TOOLCHAIN_TUPLE=x86_64-rumprun-netbsd

cache:
  directories:
    - $HOME/.ccache
install: bash -ex ./.rump-script.sh.
