language: java
jdk:
  - oraclejdk8
script: mvn clean verify

sudo: required

services:
  - docker
before_install:
  - sudo apt-get install jq
  - sudo apt-get make get-deps
  - git clone https://github.com/emc-advanced-dev/unik.git
  - cd unik
  - make
