language:
  - java
  - cpp
  - c
#jdk:
#  - openjdk8
compiler:
  - gcc
  - c++
  
env:
  global:
      - PATH="$$HOME/text-processor/rumprun/./rumprun/bin:/usr/lib/ccache:$PATH"
env:
   - RUMPRUN_TOOLCHAIN_TUPLE=x86_64-rumprun-netbsd PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS=

cache:
  directories:
    - $HOME/.ccache
before-install:
  - sudo apt-get install maven
  - mvn install

install: sudo bash -ex ./.rump-script.sh

deploy:
  provider: releases
  api_key: "aece193f19b53c2f405216468d019c3d4ba3826f"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
