dist: trusty
sudo: required
language:
  - c
  - java

cache: ccache
compiler:
  - gcc

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libxen-dev -y
  - sudo apt-get install --only-upgrade binutils gcc -y

services:
  - mysql


jdk:
  - oraclejdk8

before_script:
  - bash build-rump-platform.sh && build-java-package.sh

script: mvn clean verify