language:
  - java
  - cpp
jdk:
  - oraclejdk8
script: mvn clean verify

sudo: required
install: make get-deps
services:
  - docker
before_install:
  - sudo apt-get install jq
  - git clone https://github.com/emc-advanced-dev/unik.git
  - cd unik
  - make
  - mv _build/unik /usr/local/bin/
  - unik build  --mountpoint /tmp --args="org.springframework.boot.loader.JarLauncher" --name processor --path /root/arunsoman/text-processor  --base osv  --language java --provider virtualbox
