spring:
  application:
        name: remoteCompiler
dev:
  spring:
    datasource:
        url: jdbc:mysql://192.168.14.60:3306/tpe?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: rte
        password: bullet
        driverClassName: com.mysql.jdbc.Driver
    hostname: demo
test:
  spring:
    datasource:
      url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
      username: sa
      password:
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    hostname: demo
    
logging:
  file: logs/dev_app.log
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
server:
  port: 9000
loc:
  jarHome: /tmp/jar/
  scriptHome: /tmp/scripts/
  javaHome: /tmp/java/
  classHome: /tmp/class/