spring:
    application:
        name: remoteCompiler
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR

server:
    port: 9000

loc:
  jarHome: /tmp/jar/
  scriptHame: /tmp/scripts/
  javaHame: /tmp/java/
  classHame: /tmp/class/
