spring:
    application:
        name: processor
    datasource:
        url: jdbc:mysql://192.168.150.75:3306/tpe?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: bullet
        driverClassName: com.mysql.jdbc.Driver
        
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
    com.flytxt: DEBUG

server:
    port: 9001

compiler:
  getScript: /
  getJar: /getJar
  remoteHost: http://localhost:9000
  hostName: demo

folder:
  expireTimeInMinutes: 1
  cacheCleanUpTime: 30000
filters:
  filterNameMap:
    sample_filter_name: com.flytxt.tp.processor.filefilter.LastModifiedWindowFilter,com.flytxt.tp.processor.filefilter.RegexFilter
